### ISSUE TITLE
Error runing composer

### ISSUE THREAD

**Issue by MrGRA** [nanoninja/docker-nginx-php-mongo#1]
Hi there,
When I try to run:
docker run --rm -v $(pwd)/web/app:/app -v ~/.ssh:/root/.ssh composer/composer update

I get

 Problem 1
    - Installation request for apigen/apigen master -> satisfiable by apigen/apigen[dev-master].
    - apigen/apigen dev-master requires php ^7.1 -> your PHP version (7.0.7) does not satisfy that requirement.

Kind regards

**Comment by nanoninja** [comment]
Thanks for your feedback, I added a correction. I used the latest stable release 4.1.2 of apigen
